export { default as Category } from "./landingpage/Category";
export { default as Content } from "./Content";
export { default as Hero } from "./landingpage/Hero";
export { default as Footer } from "./Footer";
export { default as Navbar } from "./Navbar";
export { default as Filter } from "./filter/Filter";
export { default as HeroDetail } from "./detail/Hero";
export { default as Description } from "./detail/Description";
export { default as Reviews } from "./detail/Reviews";
